name: external_textures
description: A test of Flutter integrating external textures.

environment:
  sdk: ^3.7.0-0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: 1.25.15


flutter:
  uses-material-design: true

# PUBSPEC CHECKSUM: no2kui
