name: gen_keycodes
description: Generates keycode source files from various resources.

environment:
  sdk: ^3.7.0-0

resolution: workspace

dependencies:
  args: 2.7.0
  http: 1.4.0
  meta: 1.16.0
  path: 1.9.1


dev_dependencies:
  test: 1.25.15


# PUBSPEC CHECKSUM: 71jrpc
