name: customer_testing
description: Tool to run the tests listed in the flutter/tests repository.

environment:
  sdk: ^3.7.0-0

resolution: workspace

dependencies:
  args: 2.7.0
  path: 1.9.1
  glob: 2.1.3
  meta: 1.16.0

  collection: 1.19.1
  file: 7.0.1

dev_dependencies:
  test: 1.25.15


# PUBSPEC CHECKSUM: rja6dg
