name: platform_views
# This package is not intended for consumption on pub.dev.
publish_to: none
description: An integration test for embedded platform views
version: 1.0.0+1
environment:
  sdk: ^3.7.0-0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  path_provider: 2.1.5
  # This made non-transitive to allow exact pinning
  # https://github.com/flutter/flutter/issues/116376
  collection: 1.19.1
  assets_for_android_views:
    git:
      url: https://github.com/flutter/goldens.git
      ref: 64d0f6051b9b7b9933d3d16194170a38f544634a
      path: dev/integration_tests/assets_for_android_views


dev_dependencies:
  flutter_test:
    sdk: flutter
  test: 1.25.15


flutter:
  uses-material-design: true

# PUBSPEC CHECKSUM: u9uvav
