name: tests_on_bots
description: Scripts which run on bots.

environment:
  sdk: ^3.7.0-0

resolution: workspace

dependencies:
  analyzer: 7.4.5
  args: 2.7.0
  crypto: 3.0.6
  intl: 0.20.2
  file: 7.0.1
  flutter_devicelab:
    path: ../devicelab
  meta: 1.16.0
  path: 1.9.1
  platform: 3.1.6
  process: 5.0.3
  test: 1.25.15

  archive: 3.6.1
  collection: 1.19.1
  convert: 3.1.2
  glob: 2.1.3
  http: 1.4.0
  pool: 1.5.1
  shelf: 1.4.2
  shelf_static: 1.1.3
  source_span: 1.10.1
  watcher: 1.1.1
  yaml: 3.1.3


# PUBSPEC CHECKSUM: g2q9q6
