name: conductor_core
description: Flutter Automated Release Tool

publish_to: none

environment:
  sdk: ^3.7.0-0

resolution: workspace

dependencies:
  args: 2.7.0
  meta: 1.16.0
  path: 1.9.1
  process: 5.0.3
  protobuf: 4.0.0

  file: 7.0.1
  fixnum: 1.1.1
  platform: 3.1.6

dev_dependencies:
  test: 1.25.15


# PUBSPEC CHECKSUM: n78bmd
