name: tracing_tests
description: Various tests for tracing in flutter/flutter

environment:
  sdk: ^3.7.0-0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  vm_service: 15.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter


# PUBSPEC CHECKSUM: 7ocjjj
