name: stocks

environment:
  sdk: ^3.7.0-0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: 0.20.2
  http: 1.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: 1.25.15


flutter:
  generate: true
  uses-material-design: true

# PUBSPEC CHECKSUM: uh5k3v
