name: link_hook
description: 'A new Dart FFI package project.'
version: 0.0.1

environment:
  sdk: ^3.7.0-0

resolution: workspace

dependencies:
  code_assets: 0.19.0
  hooks: 0.19.0
  logging: 1.3.0
  native_toolchain_c: 0.16.0


dev_dependencies:
  test: 1.25.15


# PUBSPEC CHECKSUM: 17b3ts
