name: flutter
description: A framework for writing Flutter applications
homepage: https://flutter.dev

environment:
  sdk: ^3.7.0-0

resolution: workspace

dependencies:
  # To update these, use "flutter update-packages --force-upgrade".
  #
  # For detailed instructions, refer to:
  # https://github.com/flutter/flutter/blob/main/docs/infra/Updating-dependencies-in-Flutter.md
  characters: 1.4.0
  collection: 1.19.1
  material_color_utilities: 0.11.1
  meta: 1.16.0
  vector_math: 2.1.4
  sky_engine:
    sdk: flutter

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_goldens:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  fake_async: 1.3.3
  # To track memory leaks.
  leak_tracker_flutter_testing: 3.0.10
  leak_tracker_testing: 3.0.2
  leak_tracker: 11.0.1
  web: 1.1.1

  clock: 1.1.2
  file: 7.0.1
  path: 1.9.1
  platform: 3.1.6

# PUBSPEC CHECKSUM: 9ev34e
