name: android_semantics_testing
description: Integration testing library for Android semantics
environment:
  sdk: ^3.7.0-0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  test: 1.25.15

  meta: 1.16.0

flutter:
  uses-material-design: true

# PUBSPEC CHECKSUM: q2cu90
