name: flutter_localizations

environment:
  sdk: ^3.7.0-0

resolution: workspace

dependencies:
  # To update these, use "flutter update-packages --force-upgrade".
  #
  # For detailed instructions, refer to:
  # https://github.com/flutter/flutter/blob/main/docs/infra/Updating-dependencies-in-Flutter.md

  flutter:
    sdk: flutter
  intl: any

  path: any

dev_dependencies:
  flutter_test:
    sdk: flutter


# PUBSPEC CHECKSUM: epmht
