name: fuchsia_remote_debug_protocol
publish_to: none
description: Provides an API to test/debug Flutter applications on remote Fuchsia devices and emulators.
homepage: https://flutter.dev

environment:
  sdk: ^3.7.0-0

resolution: workspace

dependencies:
  process: 5.0.3
  vm_service: 15.0.0

  meta: 1.16.0

dev_dependencies:
  test: 1.25.15


dartdoc:
  # Exclude this package from the hosted API docs.
  nodoc: true

# PUBSPEC CHECKSUM: h0is0j
