name: web_integration
description: Integration test for web compilation.

environment:
  sdk: ^3.7.0-0

resolution: workspace

flutter:
  assets:
    - lib/a.dart
    - lib/b.dart
  uses-material-design: true

dependencies:
  flutter:
    sdk: flutter

  web: 1.1.1

  collection: 1.19.1
  meta: 1.16.0

# PUBSPEC CHECKSUM: los8ds
