name: hook_user_defines
description: 'Project for testing user-defines.'
version: 0.0.1

environment:
  sdk: ^3.7.0-0

resolution: workspace

hooks:
  user_defines:
    hook_user_defines: # package name
      magic_value: 1000

dependencies:
  hooks: 0.19.0
  logging: 1.3.0
  native_toolchain_c: 0.16.0


dev_dependencies:
  test: 1.25.15


# PUBSPEC CHECKSUM: 17b3ts
