name: android_engine_test
publish_to: none

environment:
  sdk: ^3.7.0-0

resolution: workspace

dependencies:
  android_driver_extensions:
    path: ../../tools/android_driver_extensions
  flutter:
    sdk: flutter
  flutter_driver:
    sdk: flutter

  matcher: 0.12.17
  path: 1.9.1

dev_dependencies:
  test: 1.25.15

  args: 2.7.0

# PUBSPEC CHECKSUM: almi80
