name: forbidden_from_release_tests
publish_to: 'none'

environment:
  sdk: ^3.7.0-0

resolution: workspace

dependencies:
  args: 2.7.0
  file: 7.0.1
  package_config: 2.2.0
  path: 1.9.1
  vm_snapshot_analysis: 0.7.6


# PUBSPEC CHECKSUM: vs7ni6
