name: flutter_goldens

environment:
  sdk: ^3.7.0-0

resolution: workspace

dependencies:
  # To update these, use "flutter update-packages --force-upgrade".
  #
  # For detailed instructions, refer to:
  # https://github.com/flutter/flutter/blob/main/docs/infra/Updating-dependencies-in-Flutter.md
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  crypto: 3.0.6
  file: 7.0.1
  platform: 3.1.6
  process: 5.0.3

  path: 1.9.1

# PUBSPEC CHECKSUM: rmceq8
