name: complex_layout
description: A benchmark of a relatively complex layout.

environment:
  sdk: ^3.7.0-0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_driver:
    sdk: flutter

  # To change the version of the gallery assets, edit
  #   //packages/flutter_tools/lib/src/commands/update_packages.dart
  # and run
  #   flutter update-packages --force-upgrade

  path: 1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: 1.25.15
  integration_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - packages/flutter_gallery_assets/people/square/ali.png
    - packages/flutter_gallery_assets/places/india_chettinad_silk_maker.png

# PUBSPEC CHECKSUM: misu14
