name: integration_ui
description: Flutter non-plugin UI integration tests.

environment:
  sdk: ^3.7.0-0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter
  test: 1.25.15

  path: 1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/foo.png

# PUBSPEC CHECKSUM: dv1054
