name: platform_channel

environment:
  sdk: ^3.7.0-0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: 1.25.15


flutter:
  uses-material-design: true

# PUBSPEC CHECKSUM: ng5thq
