name: gen_defaults
description: A command line script to generate Material component defaults from the token database.
version: 1.0.0

environment:
  sdk: ^3.7.0-0

resolution: workspace

dependencies:
  args: 2.7.0

dev_dependencies:
  path: 1.9.1
  test: 1.25.15


# PUBSPEC CHECKSUM: rja6dg
