name: flutter_test

environment:
  sdk: ^3.7.0-0

resolution: workspace

dependencies:
  # To update these, use "flutter update-packages --force-upgrade".
  #
  # For detailed instructions, refer to:
  # https://github.com/flutter/flutter/blob/main/docs/infra/Updating-dependencies-in-Flutter.md

  flutter:
    sdk: flutter

  # We depend on very specific internal implementation details of the
  # 'test' package, which change between versions, so when upgrading
  # this, make sure the tests are still running correctly.
  test_api: any
  matcher: any

  # Used by golden file comparator
  path: any

  # Testing utilities for dealing with async calls and time.
  fake_async: any
  clock: any

  # We import stack_trace because the test packages uses it and we
  # need to be able to unmangle the stack traces that it passed to
  # stack_trace. See https://github.com/dart-lang/test/issues/590
  stack_trace: any

  # Used by globalToLocal et al.
  vector_math: any

  # Used to detect memory leaks with `testWidgets`.
  leak_tracker_flutter_testing: any

  collection: any
  meta: any
  stream_channel: any

dev_dependencies:
  file: any
  flutter_driver:
    sdk: flutter


# PUBSPEC CHECKSUM: 7lg236
